import { useEffect } from "react";
import { Link } from "wouter";
import { setPageSeo } from "@/lib/seo";
import { PageFrame, PageTitle } from "@/components/storefront";

const content: Record<string, { title: string; eyebrow: string; intro: string; sections: Array<[string, string]> }> = {
  privacy: { eyebrow: "Chính sách", title: "Chính sách bảo mật", intro: "Trang này là bản nội dung khởi đầu cho ShoeHub. Chủ shop cần rà soát và cập nhật theo pháp nhân, đơn vị xử lý dữ liệu và quy định áp dụng trước khi công khai.", sections: [["Dữ liệu chúng tôi thu thập", "ShoeHub chỉ cần các thông tin cần thiết để xử lý đơn hàng như họ tên, số điện thoại, địa chỉ nhận hàng và email nếu bạn cung cấp."], ["Cách chúng tôi sử dụng dữ liệu", "Thông tin được dùng để xác nhận, chuẩn bị, giao hàng, hỗ trợ đơn và cải thiện trải nghiệm cửa hàng. Không lưu số thẻ trong hệ thống."], ["Bảo mật và thời hạn lưu trữ", "Dữ liệu được xử lý qua kết nối bảo mật, phân quyền theo vai trò và ghi log các thao tác quản trị cần thiết."]] },
  terms: { eyebrow: "Pháp lý", title: "Điều khoản sử dụng", intro: "Các điều khoản dưới đây là bản nháp sản phẩm, cần được chủ shop hoàn thiện cùng tư vấn pháp lý trước khi dùng cho hoạt động kinh doanh thật.", sections: [["Đặt hàng", "Đơn hàng chỉ được xác nhận sau khi ShoeHub kiểm tra thông tin, tồn kho và phương thức giao hàng."], ["Giá và thanh toán", "Giá hiển thị bằng VND. Bản đầu hỗ trợ COD và chuyển khoản thủ công; mọi thay đổi về giá được xác nhận trước khi giao."], ["Liên hệ", "Nếu có câu hỏi về đơn hàng hoặc điều khoản, liên hệ 0900 000 000 hoặc kênh người bán."]] },
  shipping: { eyebrow: "Hỗ trợ", title: "Giao nhận", intro: "ShoeHub hỗ trợ giao hàng toàn quốc và nhận tại cửa hàng. Thời gian và mức phí có thể thay đổi theo địa chỉ.", sections: [["Thời gian dự kiến", "Đơn thường được xác nhận trong ngày; cửa hàng sẽ gọi lại nếu địa chỉ hoặc thời gian giao cần làm rõ."], ["Phí giao hàng", "Phí mặc định dự kiến 30.000đ, miễn phí cho đơn từ 3.000.000đ. Phí thực tế được hiển thị trước khi bạn đặt."], ["Kiểm tra khi nhận", "Vui lòng kiểm tra hộp và sản phẩm khi nhận. Liên hệ sớm nếu có dấu hiệu đổ vỡ hoặc sai sản phẩm."]] },
  returns: { eyebrow: "Hỗ trợ", title: "Đổi sản phẩm và hoàn tiền", intro: "Nếu cần đổi size hoặc sản phẩm có vấn đề, hãy liên hệ ShoeHub trong vòng 7 ngày kể từ khi nhận hàng.", sections: [["Điều kiện", "ShoeHub tiếp nhận yêu cầu trong vòng 7 ngày, kèm mã đơn và ảnh tình trạng sản phẩm nếu cần."], ["Quy trình", "Liên hệ kênh người bán hoặc số điện thoại hỗ trợ. ShoeHub sẽ kiểm tra đơn và hướng dẫn đổi size, đổi sản phẩm hoặc hoàn tiền phù hợp."], ["Ngoại lệ", "Sản phẩm đã qua sử dụng, đã giặt hoặc quá thời gian hỗ trợ sẽ được xem xét theo từng trường hợp."]] },
};

export default function Policy({ params }: { params?: { kind?: string } }) { const kind = params?.kind ?? "privacy"; const page = content[kind] ?? content.privacy; useEffect(() => setPageSeo({ title: `${page.title} – ShoeHub`, description: page.intro }), [page.intro, page.title]); return <PageFrame><main><PageTitle eyebrow={page.eyebrow} title={page.title} body={page.intro} /><div className="container policy-layout"><nav className="policy-nav"><Link href="/policies/privacy">Bảo mật</Link><Link href="/policies/terms">Điều khoản</Link><Link href="/policies/shipping">Giao nhận</Link><Link href="/policies/returns">Đổi sản phẩm</Link></nav><article className="policy-article">{page.sections.map(([heading, text]) => <section key={heading}><h2>{heading}</h2><p>{text}</p></section>)}<div className="policy-note"><strong>Lưu ý</strong><p>Nội dung này là placeholder trong bản phát triển và chưa thay thế tư vấn pháp lý chính thức.</p></div></article></div></main></PageFrame>; }
